/*
 * Copyright 2018 Karlsruhe Institute of Technology.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package edu.kit.ocrd.workspace.entity;

import java.util.HashMap;
import java.util.Map;

/**
 * Enumeration of all possible metadata types of a section document inside a
 * METS document.
 */
public enum GroundTruthProperties {
  AGE("age"),
  HISTORICAL("age/historical"),
  MEDIEVAL("age/historical/medieval"),
  CONTEMPORARY("age/contemporary"),
  ANCIENT("age/ancient"),
  AUTOMATION("automation"),
  MANUAL("automation/manual"),
  AUTOMATED("automation/automated"),
  ASSISTED("automation/assisted"),
  PRODUCTION_METHOD("production-method"),
  PRODUCTION_METHOD_MANUAL("production-method/manual"),
  MACHINE("production-method/machine"),
  PRINTED("production-method/machine/printed"),
  TYPESET("production-method/machine/printed/typeset"),
  COMPUTER("production-method/machine/printed/computer"),
  TYPEWRITTEN("production-method/machine/typewritten"),
  CONTENT_TYPE("content-type"),
  DATA("content-type/data"),
  METADATA("content-type/metadata"),
  QUALTIY("content-type/metadata/quality"),
  PERFOMANCE_INFO("content-type/metadata/quality/performance-info"),
  FEATURES("content-type/metadata/features"),
  STRUCTURE("content-type/metadata/structure"),
  TOC("content-type/metadata/structure/toc"),
  ANNOTATIONS("content-type/metadata/annotations"),
  AUTHORSHIP("content-type/metadata/authorship"),
  SPATIAL("content-type/metadata/spatial"),
  LOCATION("content-type/metadata/spatial/location"),
  SETTINGS("content-type/settings"),
  MODEL("content-type/model"),
  LEXICON("content-type/lexicon"),
  CORPUS("content-type/corpus"),
  PRECISION("precision"),
  GROUND_TRUTH("precision/ground-truth"),
  MEASURED("precision/measured"),
  ESTIMATED("precision/estimated"),
  RANDOM("precision/random"),
  FUZZY("precision/fuzzy"),
  LICENCE("license"),
  FREE("license/free"),
  NON_COMMERCIAL("license/free/non-commercial"),
  PAID_FOR("license/paid-for"),
  PAY_ONCE("license/paid-for/pay-once"),
  VOLUME("license/paid-for/volume"),
  SUBSCRIPTION("license/paid-for/subscription"),
  OPEN_SOURCE("license/openSource"),
  PLATFORM("platform"),
  WINDOWS("platform/windows"),
  MACOS("platform/macos"),
  LINUX("platform/linux"),
  PLATFORM_INDEPENDENT("platform/platform-independent"),
  JAVA("platform/platform-independent/java"),
  WEB("platform/platform-independent/web"),
  MOBILE("platform/mobile"),
  IOS("platform/mobile/ios"),
  ANDROID("platform/mobile/android"),
  CONTENT_ENCODING("content-encoding"),
  TEXTUAL("content-encoding/textual"),
  ANNOTATED("content-encoding/textual/annotated"),
  NATURAL_LANGUAGE("content-encoding/textual/natural-language"),
  STRUCTURED("content-encoding/structured"),
  TABULAR("content-encoding/structured/tabular"),
  IMAGE("content-encoding/image"),
  COLOUR("content-encoding/image/colour"),
  BITONAL("content-encoding/image/bitonal"),
  MATHEMATICAL("content-encoding/mathematical"),
  VECTOR_BASED("content-encoding/mathematical/vector-based"),
  STROKE_BASED("content-encoding/mathematical/vector-based/stroke-based"),
  POLYGONAL("content-encoding/mathematical/polygonal"),
  ACTIVITY_DOMAIN("activityDomain"),
  COMPUTING("activityDomain/computing"),
  COMPUTING_VISUAL("activityDomain/computing/visual"),
  IMG_VID_PROC("activityDomain/computing/visual/imgVidProc"),
  GEOMETRIC("activityDomain/computing/visual/imgVidProc/geometric"),
  PIXEL_BASED("activityDomain/computing/visual/imgVidProc/pixel-based"),
  ANALYSIS_RECOGINITION("activityDomain/computing/visual/analysisRecognition"),
  ANALYSIS_RECOGINITION_TEXT("activityDomain/computing/visual/analysisRecognition/text"),
  OCR("activityDomain/computing/visual/analysisRecognition/text/ocr"),
  MATHS("activityDomain/computing/visual/analysisRecognition/text/maths"),
  DATE("activityDomain/computing/visual/analysisRecognition/text/date"),
  TABLES("activityDomain/computing/visual/analysisRecognition/tables"),
  CHARTS("activityDomain/computing/visual/analysisRecognition/charts"),
  MAPS("activityDomain/computing/visual/analysisRecognition/maps"),
  SHAPE("activityDomain/computing/visual/analysisRecognition/shape"),
  FACE("activityDomain/computing/visual/analysisRecognition/shape/face"),
  LAYOUT_ANALYSIS("activityDomain/computing/visual/analysisRecognition/layoutAnalysis"),
  GRAPHICS("activityDomain/computing/visual/graphics"),
  TEXT("activityDomain/computing/text"),
  TEXT_NATURAL_LANGUAGE("activityDomain/computing/text/naturalLanguage"),
  IDENTIFICATION("activityDomain/computing/text/naturalLanguage/identification"),
  SENTIMENT("activityDomain/computing/text/naturalLanguage/sentiment"),
  SUMMARISING("activityDomain/computing/text/naturalLanguage/summarising"),
  PART_OF_SPEECH("activityDomain/computing/text/naturalLanguage/partOfSpeech"),
  NAMED_ENTITIES("activityDomain/computing/text/naturalLanguage/namedEntities"),
  MACHINE_LEARNING("activityDomain/computing/machineLearning"),
  INFORMATION_MANAGEMENT("activityDomain/computing/informationManagement"),
  RETRIEVAL("activityDomain/computing/informationManagement/retrieval"),
  PERFORMANCE_EVAL("activityDomain/computing/performanceEval"),
  COMPARATIVE("activityDomain/computing/performanceEval/comparative"),
  IN_DEPTH("activityDomain/computing/performanceEval/in-depth"),
  FORENSIC("activityDomain/computing/forensics"),
  PROCESSING_LEVEL("processingLevel"),
  LOW_LEVEL("processingLevel/low-level"),
  HIGH_LEVEL("processingLevel/high-level"),
  DETECTION("processingLevel/high-level/detection"),
  VERIFICATION("processingLevel/high-level/detection/verification"),
  CLASSIFICATION("processingLevel/high-level/classification"),
  UNDERSTANDING("processingLevel/high-level/understanding"),
  DATA_TRANSORMATION("dataTransformation"),
  DATA_TRANSORMATION_ACQUISITION("dataTransformation/acquisition"),
  CONVERSION("dataTransformation/conversion"),
  SEGMENTATION("dataTransformation/segmentation"),
  ENHANCEMENT("dataTransformation/enhancement"),
  ENRICHTMENT("dataTransformation/enrichment"),
  ANNOTATION("dataTransformation/enrichment/annotation"),
  EXTRACTION("dataTransformation/extraction"),
  VISUALISATION("dataTransformation/visualisation"),
  ADAPTILITY("adaptability"),
  CONFIGURABLE("adaptability/configurable"),
  TRAINABLE("adaptability/trainable"),
  SUPERVISED("adaptability/trainable/supervised"),
  UNSUPERVISED("adaptability/trainable/unsupervised"),
  INTERACTIVE("adaptability/interactive"),
  GENERIC("adaptability/generic"),
  MATUITY("maturity"),
  STABLE("maturity/stable"),
  EXPERIMENTAL("maturity/experimental"),
  INDUSTRIAL("maturity/industrial"),
  ORIGINAL_SOURCE("originalSource"),
  PRODUCED("originalSource/produced"),
  PHYSICAL("originalSource/produced/physical"),
  PAPER("originalSource/produced/physical/paper"),
  BOOK("originalSource/produced/physical/paper/book"),
  NEWSPAPER("originalSource/produced/physical/paper/newspaper"),
  MAGAZINE("originalSource/produced/physical/paper/magazine"),
  JOURNAL("originalSource/produced/physical/paper/journal"),
  WHITEBOARD("originalSource/produced/physical/whiteboard"),
  POSTER("originalSource/produced/physical/poster"),
  VIRTUAL("originalSource/produced/virtual"),
  WWW("originalSource/produced/virtual/www"),
  CAPTURED("originalSource/captured"),
  SCENES("originalSource/captured/scenes"),
  SCENES_3D("originalSource/captured/scenes/3D"),
  ACQUISITION("acquisition"),
  ANALOG_TO_DIGITAL("acquisition/analogToDigital"),
  SCANNING("acquisition/analogToDigital/scanning"),
  CAMERA("acquisition/analogToDigital/camera"),
  COPIED("acquisition/copied"),
  PHOTOCOPY("acquisition/copied/photocopy"),
  CARBON_COPY("acquisition/copied/carbon-copy"),
  MICROFILM("acquisition/copied/microfilm"),
  FAX("acquisition/copied/fax"),
  SYNHESIS("acquisition/synthesis"),
  CONTENT_OF_INTEREST("contentOfInterest"),
  VISUAL("contentOfInterest/visual"),
  VISUAL_TEXT("contentOfInterest/visual/text"),
  VISUAL_GRAPHICAL("contentOfInterest/visual/graphical"),
  VISUAL_SEPARATOR("contentOfInterest/visual/graphical/separator"),
  VISUAL_BARCODE("contentOfInterest/visual/graphical/barcode"),
  VISUAL_IMAGE("contentOfInterest/visual/image"),
  PHOTOGRAPH("contentOfInterest/visual/image/photograph"),
  PHOTOGRAPH_PERSON("contentOfInterest/visual/image/photograph/person"),
  PHOTOGRAPH_FACE("contentOfInterest/visual/image/photograph/person/face"),
  DRAWING("contentOfInterest/visual/image/drawing"),
  COMPOSITE("contentOfInterest/visual/composite"),
  COMPOSITE_TABLES("contentOfInterest/visual/composite/tables"),
  COMPOSITE_CHARTS("contentOfInterest/visual/composite/charts"),
  COMPOSITE_MAPS("contentOfInterest/visual/composite/maps"),
  COMPOSITE_MATHS("contentOfInterest/visual/composite/maths"),
  COMPOSITE_CHEM("contentOfInterest/visual/composite/chem"),
  COMPOSITE_MUSIC("contentOfInterest/visual/composite/music"),
  GRANULARITY("granularity"),
  GRANULARITY_REGION("granularity/physical/document-related/region"),
  GRANULARITY_TEXT_LINE("granularity/physical/document-related/text-line"),
  GRANULARITY_WORD("granularity/physical/document-related/word"),
  GRANULARITY_GLYPH("granularity/physical/document-related/glyph"),
  GRANULARITY_DOUBLE_PAGE("granularity/physical/document-related/double-page"),
  GRANULARITY_NATURAL_LANGUAGE("granularity/physical/natural-language"),
  SENTENCE("granularity/physical/natural-language/sentence"),
  TOKEN("granularity/physical/natural-language/token"),
  SYLLABLE("granularity/physical/natural-language/syllable"),
  LOGICAL("granularity/logical"),
  LOGICAL_DOCUMENT_RELATED("granularity/logical/document-related"),
  DOCUMENT("granularity/logical/document-related/document"),
  CHAPTER("granularity/logical/document-related/chapter"),
  SECTION("granularity/logical/document-related/section"),
  ARTICLE("granularity/logical/document-related/article"),
  PARAGRAPH("granularity/logical/document-related/paragraph"),
  TABLE("granularity/logical/table"),
  TABLE_COLUMN("granularity/logical/table/column"),
  TABLE_ROW("granularity/logical/table/row"),
  TABLE_CELL("granularity/logical/table/cell"),
  CONDITION("condition"),
  NOISE("condition/noise"),
  SPECKLE("condition/noise/speckles"),
  SALT_AND_PEPPER("condition/noise/speckles/salt-and-pepper"),
  CLUTTER("condition/noise/clutter"),
  THRESHOLDING_RELATED("condition/noise/clutter/thresholding-related"),
  PRODUCTION_RELATED("condition/production-related"),
  DOCUMENT_CHARACTERISTICES("condition/production-related/document-characteristics"),
  PASTED_LIPPINGS("condition/production-related/document-characteristics/pasted-clippings"),
  TEXTURED_PAPER("condition/production-related/document-characteristics/textured-paper"),
  UNEVEN_CHARACTER_SPACING("condition/production-related/document-characteristics/uneven-character-spacing"),
  NARROW_BORDER("condition/production-related/document-characteristics/narrow-border"),
  LOW_CONTRAST("condition/production-related/document-characteristics/low-contrast"),
  HALFTONING("condition/HALFTONINGproduction-related/document-characteristics/halftoning"),
  DITHERING("condition/production-related/document-characteristics/dithering"),
  DOUCUMENT_FAULTS("condition/production-related/document-faults"),
  BLEED_THROUG("condition/production-related/document-faults/bleed-through"),
  INK_FROM_FACING("condition/production-related/document-faults/ink-from-facing"),
  SEARED_INK("condition/production-related/document-faults/smeared-ink"),
  TOUCHING_CHARS("condition/production-related/document-faults/touching-chars"),
  HORIZONTALLY("condition/production-related/document-faults/touching-chars/horizontally"),
  VERTICALLY("condition/production-related/document-faults/touching-chars/vertically"),
  UNEVEN_INK_DISTRIB("condition/production-related/document-faults/uneven-ink-distrib"),
  FILLED_IN_CHARS("condition/production-related/document-faults/filled-in-chars"),
  SORT_SHOULDER_ARTEFACTS("condition/production-related/document-faults/sort-shoulder-artefacts"),
  BROKEN_CHARS("condition/production-related/document-faults/broken-chars"),
  FAINT_CHARS("condition/production-related/document-faults/faint-chars"),
  BLURRED_CHARS("condition/production-related/document-faults/blurred-chars"),
  NON_STRAIGHT_TEXT_LINES("condition/production-related/document-faults/non-straight-text-lines"),
  WEAR("condition/wear"),
  MEDIUM_DAMAGE("condition/wear/medium-damage"),
  FOLDS("condition/wear/medium-damage/folds"),
  TEARS("condition/wear/medium-damage/tears"),
  HOLES("condition/wear/medium-damage/holes"),
  PUNCH_HOLES("condition/wear/medium-damage/holes/punch-holes"),
  UNINTENDED("condition/wear/medium-damage/holes/unintended"),
  MISSING_PARTS("condition/wear/medium-damage/missing-parts"),
  STAINS("condition/wear/medium-damage/stains"),
  SCRATCHES("condition/wear/medium-damage/scratches"),
  STAPLES("condition/wear/medium-damage/staples"),
  ADDITIONS("condition/wear/additions"),
  REPAIRS("condition/wear/additions/repairs"),
  PAPER_REPAIRS("condition/wear/additions/repairs/paper-repairs"),
  CLEAR_TABLE("condition/wear/additions/repairs/clear-tape"),
  INFORMATIVE("condition/wear/additions/informative"),
  INFORMATIVE_ANNOTATIONS("condition/wear/additions/informative/annotations"),
  STAMPS("condition/wear/additions/informative/stamps"),
  CORRECTIONS("condition/wear/additions/corrections"),
  CORRECTIONS_MANUAL("condition/wear/additions/corrections/manual"),
  AGEING("condition/ageing"),
  WARPING("condition/ageing/warping"),
  DISCOLOURATION("condition/ageing/discolouration"),
  GLOBAL("condition/ageing/discolouration/global"),
  DEGES("condition/ageing/discolouration/edges"),
  DISINTEGRATION("condition/ageing/disintegraion"),
  UNEVEN_EDGES("condition/ageing/disintegraion/uneven-edges"),
  MOULD("condition/ageing/mould"),
  FADED_CONTENT("condition/ageing/faded-content"),
  CONDITION_ACQUISTION("condition/acquisition"),
  ACQUISITION_GEOMETRIC("condition/acquisition/geometric"),
  SKEW("condition/acquisition/geometric/skew"),
  SKEW_GLOBAL("condition/acquisition/geometric/skew/global"),
  NON_UNIFORM("condition/acquisition/geometric/skew/non-uniform"),
  NINETY_DEGREE_ROTATION("condition/acquisition/geometric/90-degree-rotation"),
  UPSIDE_DOWN("condition/acquisition/geometric/upside-down"),
  PERSPECTIVE_DISTORTION("condition/acquisition/geometric/perspective-distortions"),
  PAGE_CURL("condition/acquisition/geometric/page-curl"),
  CONTENT_OR_BACKGROUND("condition/acquisition/content-or-background"),
  INCOMPLETE_CAPTUREE("condition/acquisition/content-or-background/incomplete-capture"),
  TIGHT_MARGINS("condition/acquisition/content-or-background/tight-margins"),
  INCLUDED_OBJECTS("condition/acquisition/content-or-background/included-objects"),
  PRECEEDING_OR_PROCEEDING("condition/acquisition/content-or-background/included-objects/preceeding-or-proceeding"),
  MEDIUM_STRUCTURE("condition/acquisition/content-or-background/included-objects/medium-structure"),
  CLIPS("condition/acquisition/content-or-background/included-objects/clips"),
  FINGERS("condition/acquisition/content-or-background/included-objects/fingers"),
  INSECTS("condition/acquisition/content-or-background/included-objects/insects"),
  BACKGROUND("condition/acquisition/content-or-background/included-objects/background"),
  METHOD_FLWAS("condition/acquisition/method-flaws"),
  IMAGING("condition/acquisition/method-flaws/imaging"),
  SHOW_THROUGE("condition/acquisition/method-flaws/imaging/show-through"),
  UNEVEN_ILLUMINATION("condition/acquisition/method-flaws/imaging/uneven-illumination"),
  SHADOWS("condition/acquisition/method-flaws/imaging/uneven-illumination/shadows"),
  IMAGING_OUT_OF_FOCUS("condition/acquisition/method-flaws/imaging/out-of-focus"),
  IMAGING_LOW_CONTRAST("condition/acquisition/method-flaws/imaging/low-contrast"),
  MISSING_CONTENT("condition/acquisition/method-flaws/imaging/missing-content"),
  THRESHOLDING("condition/acquisition/method-flaws/imaging/missing-content/thresholding"),
  DATA_ATTRIBUTES("data-attributes"),
  LANGUAGE("data-attributes/language"),
  NATURAL("data-attributes/language/natural"),
  ENGLISH("data-attributes/language/natural/english"),
  MIXED("data-attributes/language/mixed"),
  DOCUMENT_RELATED("data-attributes/document-related"),
  DOCUMENT_RELATED_VISUAL("data-attributes/document-related/visual"),
  DOCUMENT_RELATED_TEXT("data-attributes/document-related/visual/text"),
  SCRIPT("data-attributes/document-related/visual/text/script"),
  LATIN("data-attributes/document-related/visual/text/script/latin"),
  BRAILLE("data-attributes/document-related/visual/text/script/braille"),
  FONT("data-attributes/document-related/visual/text/font"),
  CURSIVE("data-attributes/document-related/visual/text/font/cursive"),
  MONOSPACE("data-attributes/document-related/visual/text/font/monospace"),
  TYPEFACE("data-attributes/document-related/visual/text/font/typeface"),
  BLACKLETTER("data-attributes/document-related/visual/text/font/typeface/blackletter"),
  ANTIQUA("data-attributes/document-related/visual/text/font/typeface/antiqua"),
  MANUSCRIPT("data-attributes/document-related/visual/text/font/typeface/manuscript"),
  DECORATED("data-attributes/document-related/visual/text/font/decorated"),
  FLOURISHES("data-attributes/document-related/visual/text/font/decorated/flourishes"),
  MULTI_COLOUR("data-attributes/document-related/visual/text/font/decorated/multi-colour"),
  REVERSE_VIDEO("data-attributes/document-related/visual/text/font/decorated/reverse-video"),
  MULIT_FONT("data-attributes/document-related/visual/text/font/multi-font"),
  TYPEFACES("data-attributes/document-related/visual/text/font/multi-font/typefaces"),
  FONTSIZES("data-attributes/document-related/visual/text/font/multi-font/font-sizes"),
  DROP_CAPS("data-attributes/document-related/visual/text/drop-caps"),
  COLUMNS("data-attributes/document-related/visual/columns"),
  ONE("data-attributes/document-related/visual/columns/one"),
  TWO("data-attributes/document-related/visual/columns/two"),
  MULTIPLE("data-attributes/document-related/visual/columns/multiple"),
  ROTATED_CONTENT("data-attributes/document-related/visual/rotated-content"),
  COMPLEX_BACKGROUND("data-attributes/document-related/visual/complex-background"),
  WATERMARKS("data-attributes/document-related/visual/complex-background/watermarks"),
  IMPRESSIONS("data-attributes/document-related/visual/complex-background/impressions"),
  ILLUSTRATIONS("data-attributes/document-related/visual/illustrations"),
  MULIT_COLOUR("data-attributes/document-related/visual/illustrations/multi-colour"),
  DECORATIONS("data-attributes/document-related/visual/decorations"),
  FRAMES("data-attributes/document-related/visual/decorations/frames"),
  LINE_ART("data-attributes/document-related/visual/line-art"),
  CAPTCHAS("data-attributes/document-related/visual/captchas"),
  STRUCTURAL("data-attributes/document-related/structural"),
  RUNNING_TITLES("data-attributes/document-related/structural/running-titles"),
  FOOTNOTES("data-attributes/document-related/structural/footnotes"),
  REFERENCES("data-attributes/document-related/structural/references"),
  TOPIC("topic"),
  ECONOMY("topic/economy"),
  FINANCIAL("topic/economy/financial"),
  CHECKS("topic/economy/financial/checks"),
  INVOICES("topic/economy/financial/invoices"),
  BANK_NOTES("topic/economy/financial/bank-notes"),
  SOCIAL_SCIENCE("topic/social-science"),
  SOCIAL_SCIENCE_MAPS("topic/social-science/maps"),
  TOPOGRAPHICAL("topic/social-science/maps/topographical"),
  ROAD("topic/social-science/maps/road"),
  LAND_USE("topic/social-science/maps/land-use"),
  TRAFFIC("topic/social-science/traffic"),
  NUMBER_LATES("topic/social-science/traffic/number-plates"),
  SIGNS("topic/social-science/traffic/signs"),
  ENGINEERING("topic/engineering"),
  ARCHITECTURE("topic/engineering/architecture"),
  FLOOR_LANS("topic/engineering/architecture/floor-plans"),
  DRAWINGS("topic/engineering/architecture/drawings"),
  MEDICAL("topic/engineering/medical"),
  ENGINEERING_DRAWINGS("topic/engineering/engineering-drawings"),
  PATENTS("topic/engineering/patents"),
  MEDIA("topic/media"),
  ADVERTS("topic/media/adverts"),
  COMUPUTING("topic/computing"),
  USER_GROUPS("user-groups"),
  ADMINS("user-groups/admins"),
  WORKFLOW_EXPERTS("user-groups/workflow-experts"),
  DOMAIN_EXPERTS("user-groups/domain-experts"),
  DIA("user-groups/domain-experts/dia"),
  LIBRARIANS("user-groups/domain-experts/librarians");

  // Reverse lookup map for getting enum from its text representation
  private static final Map<String, GroundTruthProperties> lookup = new HashMap<String, GroundTruthProperties>();
  /**
   * Text representation of enumeration.
   */
  private final String textRepresentation;

  static {
    for (GroundTruthProperties gtp : GroundTruthProperties.values()) {
      lookup.put(gtp.textRepresentation, gtp);
    }
  }

  /**
   * Constructor for enum.
   *
   * @param pTextRepresentation text representation of enumeration.
   */
  GroundTruthProperties(final String pTextRepresentation) {
    this.textRepresentation = pTextRepresentation;
  }

  @Override
  public String toString() {
    return textRepresentation;
  }

  /**
   * Get Enum from text representation.
   * 
   * @param textRepresentation Text representation.
   * 
   * @return 
   */ 
   public static GroundTruthProperties get(String textRepresentation) {
    return lookup.get(textRepresentation);
  }

}
